### ISSUE TITLE
[Help]: Failed install. 

### ISSUE THREAD

**Issue by Brian-Eph** [zwave-js/node-red-contrib-zwave-js#119]
-----------------------------------------------------------
2021-10-03T19:35:20.436Z Install : node-red-contrib-zwave-js 6.1.1

2021-10-03T19:35:21.706Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-zwave-js@6.1.1
2021-10-03T19:35:43.453Z [err] npm
2021-10-03T19:35:43.453Z [err]  ERR! code 1
2021-10-03T19:35:43.453Z [err] npm ERR! path
2021-10-03T19:35:43.453Z [err]  /config/node-red/node_modules/node-red-contrib-zwave-js
2021-10-03T19:35:43.458Z [err] npm ERR! command failed
2021-10-03T19:35:43.458Z [err] npm ERR! command sh -c npm install --build-from-source --production @serialport/bindings@9.2.1 && npm install --build-from-source --production serialport@9.2.1
2021-10-03T19:35:43.458Z [err] npm ERR!
2021-10-03T19:35:43.458Z [err]  npm ERR! code 1
2021-10-03T19:35:43.458Z [err] npm ERR! npm ERR! path /config/node-red/node_modules/node-red-contrib-zwave-js/node_modules/@serialport/bindings
2021-10-03T19:35:43.458Z [err] npm ERR! npm ERR! command failed
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info it worked if it ends with ok
2021-10-03T19:35:43.459Z [err] npm
2021-10-03T19:35:43.459Z [err]  ERR! npm ERR! gyp info using node-gyp@7.1.2
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info using node@14.17.6 | linux | arm64
2021-10-03T19:35:43.459Z [err] npm ERR!
2021-10-03T19:35:43.459Z [err]  npm ERR! gyp info find Python using Python version 3.9.5 found at "/usr/bin/python3"
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn /usr/bin/python3
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn args [
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn args   'binding.gyp',
2021-10-03T19:35:43.459Z [err] npm ERR!
2021-10-03T19:35:43.459Z [err]  npm ERR! gyp info spawn args   '-f',
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn args   'make',
2021-10-03T19:35:43.459Z [err] npm ERR!
2021-10-03T19:35:43.459Z [err]  npm ERR! gyp info spawn args   '-I',
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn args   '/config/node-red/node_modules/node-red-contrib-zwave-js/node_modules/@serialport/bindings/build/config.gypi',
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn args   '-I',
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn args   '-I',
2021-10-03T19:35:43.459Z [err] npm
2021-10-03T19:35:43.459Z [err]  ERR! npm ERR! gyp info spawn args   '/root/.cache/node-gyp/14.17.6/include/node/common.gypi',
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2021-10-03T19:35:43.459Z [err] npm
2021-10-03T19:35:43.459Z [err]  ERR! npm ERR! gyp info spawn args   '-Dvisibility=default',
2021-10-03T19:35:43.459Z [err] npm ERR! npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.17.6',
2021-10-03T19:35:43.460Z [err] npm ERR! npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2021-10-03T19:35:43.460Z [err] npm 
2021-10-03T19:35:43.460Z [err] ERR! npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.17.6/<(target_arch)/node.lib',
2021-10-03T19:35:43.460Z [err] npm ERR!
2021-10-03T19:35:43.460Z [err]  npm ERR! gyp info spawn args   '-Dmodule_root_dir=/config/node-red/node_modules/node-red-contrib-zwave-js/node_modules/@serialport/bindings',
2021-10-03T19:35:43.460Z [err] npm ERR! npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2021-10-03T19:35:43.460Z [err] npm
2021-10-03T19:35:43.460Z [err]  ERR! npm ERR! gyp info spawn args   '--depth=.',
2021-10-03T19:35:43.460Z [err] npm ERR!
2021-10-03T19:35:43.460Z [err]  npm ERR! gyp info spawn args   '--no-parallel',
2021-10-03T19:35:43.460Z [err] npm ERR! npm ERR! gyp info spawn args   '--generator-output',
2021-10-03T19:35:43.460Z [err] npm ERR! npm ERR! gyp info spawn args   'build',
2021-10-03T19:35:43.460Z [err] npm 
2021-10-03T19:35:43.460Z [err] ERR! npm ERR! gyp info spawn args   '-Goutput_dir=.'
2021-10-03T19:35:43.460Z [err] npm ERR!
2021-10-03T19:35:43.460Z [err]  npm ERR! gyp info spawn args ]
2021-10-03T19:35:43.460Z [err] npm ERR! npm ERR! gyp ERR! build error 
2021-10-03T19:35:43.460Z [err] npm ERR! npm ERR! gyp ERR! stack Error: not found: make
2021-10-03T19:35:43.460Z [err] npm 
2021-10-03T19:35:43.460Z [err] ERR! npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
2021-10-03T19:35:43.460Z [err] npm ERR!
2021-10-03T19:35:43.460Z [err]  npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
2021-10-03T19:35:43.460Z [err] npm ERR! npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-10-03T19:35:43.460Z [err] npm ERR! npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
2021-10-03T19:35:43.460Z [err] npm 
2021-10-03T19:35:43.460Z [err] ERR! npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
2021-10-03T19:35:43.460Z [err] npm ERR!
2021-10-03T19:35:43.460Z [err]  npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-10-03T19:35:43.460Z [err] npm ERR! npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
2021-10-03T19:35:43.460Z [err] npm ERR! npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
2021-10-03T19:35:43.460Z [err] npm 
2021-10-03T19:35:43.461Z [err] ERR! npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-10-03T19:35:43.461Z [err] npm ERR!
2021-10-03T19:35:43.461Z [err]  npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-10-03T19:35:43.461Z [err] npm ERR! npm ERR! gyp ERR! System Linux 5.10.62
2021-10-03T19:35:43.461Z [err] npm
2021-10-03T19:35:43.461Z [err]  ERR! npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-10-03T19:35:43.461Z [err] npm ERR!
2021-10-03T19:35:43.461Z [err]  npm ERR! gyp ERR! cwd /config/node-red/node_modules/node-red-contrib-zwave-js/node_modules/@serialport/bindings
2021-10-03T19:35:43.461Z [err] npm ERR! npm ERR! gyp ERR! node -v v14.17.6
2021-10-03T19:35:43.461Z [err] npm ERR! npm ERR! gyp ERR! node-gyp -v v7.1.2
2021-10-03T19:35:43.461Z [err] npm 
2021-10-03T19:35:43.461Z [err] ERR! npm ERR! gyp ERR! not ok
2021-10-03T19:35:43.461Z [err] npm ERR!
2021-10-03T19:35:43.461Z [err]  
2021-10-03T19:35:43.461Z [err] npm ERR!
2021-10-03T19:35:43.461Z [err]  npm ERR! A complete log of this run can be found in:
2021-10-03T19:35:43.461Z [err] npm ERR! npm ERR!     /root/.npm/_logs/2021-10-03T19_35_42_407Z-debug.log
2021-10-03T19:35:43.501Z [err] 
2021-10-03T19:35:43.501Z [err] npm ERR! A complete log of this run can be found in:
2021-10-03T19:35:43.501Z [err] npm ERR!     /root/.npm/_logs/2021-10-03T19_35_43_467Z-debug.log
2021-10-03T19:35:43.531Z rc=1reenshots or drawings here if they help your explanation.

### Any more details?

Installed on Home Assistant Blue 

### Version

6.1.1

### Node-RED Version

2.0.6

### What hardware are you using?

Other

**Comment by marcus-j-davies** [comment]
Hello,

is this a new install or an update?

**Comment by marcus-j-davies** [comment]
Installing into HA is a little different.

edit the node-red plugin, and do the following.

```yaml
system_packages:
  - make
  - python3
  - g++
  - gcc
  - linux-headers
  - udev
npm_packages:
  - serialport 
  - node-red-contrib-zwave-js
```

**Comment by Brian-Eph** [comment]
Ok - I did not see that info before - thank you. I guess I will just keep using the events node. I thought this would be a cleaner way but if it was not made to work on HA then I won't use it. Much appreciated.
