### ISSUE TITLE
[Bug]: Can't install node

### ISSUE THREAD

**Issue by MRobi1** [zwave-js/node-red-contrib-zwave-js#160]
### What happened?

Unable to install nodes.
This is the log from node red.
Using home assistant node red addon.

`2021-12-10T14:04:21.711Z Install : node-red-contrib-zwave-js 6.4.0

2021-12-10T14:04:21.347Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-zwave-js@6.4.0
2021-12-10T14:04:32.561Z [err] npm
2021-12-10T14:04:32.562Z [err]  ERR! code 1
2021-12-10T14:04:32.562Z [err] npm ERR!
2021-12-10T14:04:32.562Z [err]  path /config/node-red/node_modules/@serialport/bindings
2021-12-10T14:04:32.565Z [err] npm
2021-12-10T14:04:32.565Z [err]  ERR! command failed
2021-12-10T14:04:32.565Z [err] npm ERR!
2021-12-10T14:04:32.566Z [err]  command
2021-12-10T14:04:32.566Z [err]  sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2021-12-10T14:04:32.566Z [err] npm ERR!
2021-12-10T14:04:32.566Z [err]  prebuild-install WARN install No prebuilt binaries found (target=16.13.1 runtime=node arch=x64 libc=musl platform=linux)
2021-12-10T14:04:32.566Z [err] npm 
2021-12-10T14:04:32.566Z [err] ERR! gyp info it worked if it ends with ok
2021-12-10T14:04:32.566Z [err] npm
2021-12-10T14:04:32.566Z [err]  ERR!
2021-12-10T14:04:32.567Z [err]  gyp info using node-gyp@8.3.0
2021-12-10T14:04:32.567Z [err] npm
2021-12-10T14:04:32.567Z [err]  ERR! gyp info using node@16.13.1 | linux | x64
2021-12-10T14:04:32.567Z [err] npm ERR!
2021-12-10T14:04:32.567Z [err]  gyp info find Python using Python version 3.9.7 found at "/usr/bin/python3"
2021-12-10T14:04:32.567Z [err] npm ERR!
2021-12-10T14:04:32.567Z [err]  gyp info spawn /usr/bin/python3
2021-12-10T14:04:32.567Z [err] npm ERR!
2021-12-10T14:04:32.567Z [err]  gyp info spawn args [
2021-12-10T14:04:32.567Z [err] npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2021-12-10T14:04:32.567Z [err] npm
2021-12-10T14:04:32.567Z [err]  ERR! gyp info spawn args   'binding.gyp',
2021-12-10T14:04:32.567Z [err] npm ERR! gyp info spawn args   '-f',
2021-12-10T14:04:32.567Z [err] npm ERR! gyp info spawn args   'make',
2021-12-10T14:04:32.567Z [err] npm 
2021-12-10T14:04:32.568Z [err] ERR! gyp info spawn args   '-I',
2021-12-10T14:04:32.568Z [err] npm ERR! gyp info spawn args   '/config/node-red/node_modules/@serialport/bindings/build/config.gypi',
2021-12-10T14:04:32.568Z [err] npm ERR! gyp info spawn args   '-I',
2021-12-10T14:04:32.568Z [err] npm 
2021-12-10T14:04:32.568Z [err] ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2021-12-10T14:04:32.568Z [err] npm ERR! gyp info spawn args   '-I',
2021-12-10T14:04:32.568Z [err] npm
2021-12-10T14:04:32.568Z [err]  ERR! gyp info spawn args   '/root/.cache/node-gyp/16.13.1/include/node/common.gypi',
2021-12-10T14:04:32.568Z [err] npm ERR!
2021-12-10T14:04:32.568Z [err]  gyp info spawn args   '-Dlibrary=shared_library',
2021-12-10T14:04:32.568Z [err] npm ERR! gyp info spawn args   '-Dvisibility=default',
2021-12-10T14:04:32.568Z [err] npm
2021-12-10T14:04:32.568Z [err]  ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.13.1',
2021-12-10T14:04:32.568Z [err] npm ERR!
2021-12-10T14:04:32.568Z [err]  gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2021-12-10T14:04:32.568Z [err] npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.13.1/<(target_arch)/node.lib',
2021-12-10T14:04:32.568Z [err] npm
2021-12-10T14:04:32.568Z [err]  ERR! gyp info spawn args   '-Dmodule_root_dir=/config/node-red/node_modules/@serialport/bindings',
2021-12-10T14:04:32.568Z [err] npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2021-12-10T14:04:32.568Z [err] npm
2021-12-10T14:04:32.568Z [err]  ERR! gyp info spawn args   '--depth=.',
2021-12-10T14:04:32.568Z [err] npm ERR!
2021-12-10T14:04:32.569Z [err]  gyp info spawn args   '--no-parallel',
2021-12-10T14:04:32.569Z [err] npm ERR!
2021-12-10T14:04:32.569Z [err]  gyp info spawn args   '--generator-output',
2021-12-10T14:04:32.569Z [err] npm 
2021-12-10T14:04:32.569Z [err] ERR! gyp info spawn args   'build',
2021-12-10T14:04:32.569Z [err] npm 
2021-12-10T14:04:32.569Z [err] ERR! gyp info spawn args   '-Goutput_dir=.'
2021-12-10T14:04:32.569Z [err] npm ERR! gyp info spawn args ]
2021-12-10T14:04:32.569Z [err] npm ERR! gyp ERR! build error 
2021-12-10T14:04:32.569Z [err] npm 
2021-12-10T14:04:32.569Z [err] ERR! gyp ERR! stack Error: not found: make
2021-12-10T14:04:32.569Z [err] npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
2021-12-10T14:04:32.569Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
2021-12-10T14:04:32.569Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-12-10T14:04:32.569Z [err] npm
2021-12-10T14:04:32.569Z [err]  ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
2021-12-10T14:04:32.569Z [err] npm ERR!
2021-12-10T14:04:32.569Z [err]  gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
2021-12-10T14:04:32.569Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-12-10T14:04:32.570Z [err] npm ERR!
2021-12-10T14:04:32.570Z [err]  gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
2021-12-10T14:04:32.570Z [err] npm ERR!
2021-12-10T14:04:32.570Z [err]  gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
2021-12-10T14:04:32.570Z [err] npm ERR!
2021-12-10T14:04:32.570Z [err]  gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-12-10T14:04:32.570Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-12-10T14:04:32.570Z [err] npm ERR! gyp ERR! System Linux 5.10.75
2021-12-10T14:04:32.570Z [err] npm ERR!
2021-12-10T14:04:32.570Z [err]  gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-12-10T14:04:32.570Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2021-12-10T14:04:32.570Z [err] npm
2021-12-10T14:04:32.570Z [err]  ERR! gyp ERR! node -v v16.13.1
2021-12-10T14:04:32.570Z [err] npm 
2021-12-10T14:04:32.570Z [err] ERR! gyp ERR! node-gyp -v v8.3.0
2021-12-10T14:04:32.570Z [err] npm ERR!
2021-12-10T14:04:32.570Z [err]  gyp ERR! not ok
2021-12-10T14:04:32.589Z [err] 
2021-12-10T14:04:32.589Z [err] npm ERR! A complete log of this run can be found in:
2021-12-10T14:04:32.589Z [err] npm ERR!     /root/.npm/_logs/2021-12-10T14_04_32_574Z-debug.log
2021-12-10T14:04:32.607Z rc=1`

### How to reproduce?

npm install node-red-contrib-zwave-js

### Version

8.8.3

### Node-RED Version

v2.1.4

### What hardware are you seeing the problem on?

Other

**Comment by marcus-j-davies** [comment]
Hi there,

On the basis you don't want to use the HA Z-Wave plug-in, and want to manage Z-Wave all within Node Red, see her.

https://github.com/zwave-js/node-red-contrib-zwave-js/wiki/getting-started#home-assistant-users

**Comment by marcus-j-davies** [comment]
I will close this, please re-open if you feel the need.
