### ISSUE TITLE
[Warning]: MaxListenersExceededWarning

### ISSUE THREAD

**Issue by ralphwetzel** [zwave-js/node-red-contrib-zwave-js#170]
### What happened?

I've quite a 'small' HomeAutomation setup - some Smoke Sensors & 10 Roller Shutters, all Z-Wave powered.
Each group is controlled via its own logic, placed into a subflow & then reused for each of the devices.
In total, 14 nodes "zwave - device" are used. 
When node-red is launched or a change is deployed that triggers a restart of the z-wave driver, the warning stated below is issued.

### How to reproduce?

Add more than 10 nodes "zwave - device" to node-red. Restart the flows. Voila!

### Version

6.4.1

### Node-RED Version

2.1.4

### What hardware are you seeing the problem on?

Raspberry Pi

### Relevant Z-Wave-JS log output

```shell
(node:2012) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 zwjs:node:event:all listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:475:17)
    at EventEmitter.addListener (events.js:497:10)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/events.js:38:33)
    at new Init (/home/pi/mnt/node-red/node_modules/node-red-contrib-zwave-js/zwave-js/zwave-device.js:104:16)
    at Object.createNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/util.js:87:27)
    at Subflow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:206:48)
    at Subflow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Subflow.js:313:15)
    at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:224:41)
    at start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:371:33)
```

**Comment by marcus-j-davies** [comment]
Hi @ralphwetzel,

Thanks for the report.

10 is the max listeners per event type before a warning is triggered by **EventEmitter**
Here you have 11 subscribed to **zwjs:node:event:all**.

According to **EventEmitter** docs - this is just a warning - is this impacting your logic?
I am not challenging it 😅  - I just want to know the severity.

We use Node-Red's built in **EventEmitter** - so we don't want to start changing its defaults.
Can you switch to using **Multiple Nodes** mode instead.

I might look into using a different mechanism soon.

**Comment by ralphwetzel** [comment]
Hi @marcus-j-davies !
thank you for your fast reply.
First: I can work around this warning - and the flows even seem to run as they should. It was just an anomaly I thought worth to be reported. BTW: Thank you for this library. Great piece of software!
Second: I found a [discussion](https://discourse.nodered.org/t/node-developers-how-to-use-setmaxlisteners-using-red-events/50154) concerning this topic. This could show you the direction to setup a custom EventEmitter. Seems not to be too difficult to implement...

**Comment by marcus-j-davies** [comment]
@ralphwetzel 

Just as an update - I have instantiated an internal **Emitter** with a max listener of 0 😉.
this seems to work with no problems - its in my 6.5.0 branch - which I will look to release soon.
