### ISSUE TITLE
Install Failed - jQuery

### ISSUE THREAD

**Issue by Rev-777** [zwave-js/node-red-contrib-zwave-js#21]
Node-RED 8.0.1 on a Pi 4/HA Supervised.

Unable to install:

```
2021-02-04T15:12:49.375Z Install : node-red-contrib-zwave-js 1.3.1

2021-02-04T15:12:49.398Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-zwave-js@1.3.1
2021-02-04T15:13:01.882Z [out] 
2021-02-04T15:13:01.882Z [out] > @serialport/bindings@9.0.4 install /config/node-red/node_modules/@serialport/bindings
2021-02-04T15:13:01.882Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2021-02-04T15:13:01.882Z [out] 
2021-02-04T15:13:02.853Z [err] prebuild-install
2021-02-04T15:13:02.854Z [err]  WARN install No prebuilt binaries found (target=14.15.4 runtime=node arch=arm libc=musl platform=linux)
2021-02-04T15:13:04.561Z [err] gyp
2021-02-04T15:13:04.562Z [err]  ERR!
2021-02-04T15:13:04.562Z [err]  build error 
2021-02-04T15:13:04.563Z [err] gyp 
2021-02-04T15:13:04.564Z [err] ERR! stack Error: not found: make
2021-02-04T15:13:04.564Z [err] gyp
2021-02-04T15:13:04.564Z [err]  ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2021-02-04T15:13:04.564Z [err] gyp 
2021-02-04T15:13:04.564Z [err] ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2021-02-04T15:13:04.564Z [err] gyp
2021-02-04T15:13:04.564Z [err]  ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2021-02-04T15:13:04.564Z [err] gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2021-02-04T15:13:04.564Z [err] gyp
2021-02-04T15:13:04.564Z [err]  ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-02-04T15:13:04.564Z [err] gyp 
2021-02-04T15:13:04.565Z [err] ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-02-04T15:13:04.565Z [err] gyp ERR! 
2021-02-04T15:13:04.565Z [err] stack     at FSReqCallback.oncomplete (fs.js:183:21)
2021-02-04T15:13:04.565Z [err] gyp ERR! 
2021-02-04T15:13:04.566Z [err] System Linux 5.4.79-v7l+
2021-02-04T15:13:04.566Z [err] gyp ERR! 
2021-02-04T15:13:04.566Z [err] command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-02-04T15:13:04.566Z [err] gyp ERR! cwd
2021-02-04T15:13:04.566Z [err]  /config/node-red/node_modules/@serialport/bindings
2021-02-04T15:13:04.566Z [err] gyp ERR! node -v
2021-02-04T15:13:04.566Z [err]  v14.15.4
2021-02-04T15:13:04.566Z [err] gyp ERR! node-gyp -v v5.1.0
2021-02-04T15:13:04.566Z [err] gyp ERR! not ok 
2021-02-04T15:13:05.412Z [err] npm WARN
2021-02-04T15:13:05.413Z [err]  multiple-select@1.5.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
2021-02-04T15:13:05.413Z [err] 
2021-02-04T15:13:05.446Z [err] npm ERR! 
2021-02-04T15:13:05.446Z [err] code ELIFECYCLE
2021-02-04T15:13:05.446Z [err] npm ERR! errno 1
2021-02-04T15:13:05.465Z [err] npm ERR! @serialport/bindings@9.0.4 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2021-02-04T15:13:05.465Z [err] npm ERR! Exit status 1
2021-02-04T15:13:05.465Z [err] npm ERR! 
2021-02-04T15:13:05.465Z [err] npm ERR! Failed at the @serialport/bindings@9.0.4 install script.
2021-02-04T15:13:05.466Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-02-04T15:13:05.487Z [err] 
2021-02-04T15:13:05.487Z [err] npm ERR! A complete log of this run can be found in:
2021-02-04T15:13:05.487Z [err] npm ERR!     /root/.npm/_logs/2021-02-04T15_13_05_478Z-debug.log
2021-02-04T15:13:05.506Z rc=1
```

Found jQuery on npm and installed, tried this again with identical error.

**Comment by marcus-j-davies** [comment]
jQuery?

You need to install `make`, and may need to install serial ports directly.
see https://github.com/zwave-js/node-red-contrib-zwave-js/issues/17 for a fix.

**Comment by marcus-j-davies** [comment]
@hufftheweevil,

We seem to be seeing this with HA, being uninvolved with HA, is this normal?, is there a reason why HA does not want to install certain deps?

**Comment by hufftheweevil** [comment]
Honestly, I don't know enough about HA to know if it's "normal" or not. But you're right that it is HA-related. Since @nappyjim was able to fix it with [some config settings](https://github.com/zwave-js/node-red-contrib-zwave-js/issues/17#issuecomment-772894575), maybe we should just add that info to the readme.

**Comment by marcus-j-davies** [comment]
Ok,

I think this is the way Red has been integrated into HA - seems as if it's been cannibalised.
[this](https://community.home-assistant.io/t/unable-to-install-rfxtrx-nodes-in-hassio-node-red-addon/88867) also backs up @nappyjim approach.

**Comment by czech12** [comment]
Hi,

I was able to get the npm installed using @nappyjim method.  However, I'm confused by the configuration.

Another HA user and I have the Node-Red Add-On installed as well as the new Zwave JS Addon.

The Zwave JS Addon already connects to my USB Zwave Hub and I don't think the Zwave JS Node-Red NPM can connect to it at the same time.

I was expecting this Node-Red NPM to connect to the Zwave JS Addon that is already running in HA.  Is it not possible to use both the HA Zwave JS Addon and the Zwave JS NodeRed NPM at the same time?

**Comment by marcus-j-davies** [comment]
Hi,

The HA zwave js add-on is for HA.
This add-on is nothing to do with HA.

It’s for node-red, which just so happens to also be available as an add-on for HA - which where the confusion might be.

The 2 plugins are entirely different things.
One is for HA, the other is for node-red.

Hope that helps.

**Comment by czech12** [comment]
> Hi, The HA zwave js add-on is for HA. This add-on is nothing to do with HA. It’s for node-red, which just so happens to also be available as an add-on for HA - which where the confusion might be. The 2 plugins are entirely different things. One is for HA, the other is for node-red. Hope that helps.
> […](#)
> Sent from my iPhone
> On 4 Feb 2021, at 21:57, czech12 ***@***.***> wrote: ﻿ Hi, I was able to get the npm installed using @nappyjim method. However, I'm confused by the configuration. Another HA user and I have the Node-Red Add-On installed as well as the new Zwave JS Addon. The Zwave JS Addon already connects to my USB Zwave Hub and I don't think the Zwave JS Node-Red NPM can connect to it at the same time. I was expecting this Node-Red NPM to connect to the Zwave JS Addon that is already running in HA. Is it not possible to use both the HA Zwave JS Addon and the Zwave JS NodeRed NPM at the same time? — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, I'm starting to think this NPM isn't for what all us HA people thought it was for.  HA just released a new Zwave JS integration in the latest release which is why you are probably getting all this traffic.

Us HA People are looking for a Node-Red NPM that will communicate to the Zwave JS instance running as an AddOn in HA.  I don't think it exists...   YET!   =)

Thanks again!

**Comment by marcus-j-davies** [comment]
That would actually make a lot of sense.
but yup - this one is for node-red, regardless of its host/container.

**Comment by hufftheweevil** [comment]
I'm not positive, but I think the general HA community is leaning towards [zwave-js-server](https://github.com/zwave-js/zwave-js-server) as the official Zwave add-on. However, [zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt) could also be used. It all really depends on how you want to wire it up to HA and Node-RED.

In my case, I use HA as more of a glorified container system. My HA entities are very limited and almost everything takes place in Node-RED. So using this package works just fine for me.

**Comment by marcus-j-davies** [comment]
Closing as per discussions above.
