### ISSUE TITLE
[Help]: Controller node with Aeotec Gen 5 in docker on Portainer returns "Failed to initialize the driver"

### ISSUE THREAD

**Issue by devironglove** [zwave-js/node-red-contrib-zwave-js#228]
### How can we help?

After configuring my Zwave Controller node, I get an error "Failed to initialize the driver"

Current setup : 

Controller is a Aeotec Gen5

- Portainer running dockers 
  - 1 docker with Zwave2mqtt to handle the network 
  - 1 docker with Nodered
- I mapped my USB device to /dev/zwave in Portainer (working like a charm with another container Zwavejs2mqtt)
- It's mapped aswell to /dev/zwave on my NodeRed instance. 

First, I had some "Permission denied" so had to change my docker user in my stack.
After that, I get some error :
`ZWaveError: Failed to initialize the driver: ZWaveError: Timeout while waiting for a response from the controller (ZW0200)
    at Driver.sendMessage (/data/node_modules/zwave-js/src/lib/driver/Driver.ts:3547:23)
    at ZWaveController.interview (/data/node_modules/zwave-js/src/lib/controller/Controller.ts:773:22)
    at Driver.initializeControllerAndNodes (/data/node_modules/zwave-js/src/lib/driver/Driver.ts:1179:27)
    at Immediate.<anonymous> (/data/node_modules/zwave-js/src/lib/driver/Driver.ts:924:5) (ZW0100)`

Could it be that because the USB is being used in Zwavejs2Mqtt, NodeRed can't initialize the communication with the controller?
How can I check further what the reason could be?

### Version

7.1.2

### Node-RED Version

V2.2.2

### What hardware are you using?

Other

**Comment by marcus-j-davies** [comment]
Hi @devironglove 

> Could it be that because the USB is being used in Zwavejs2Mqtt,

Indeed, a serial device can't be used by more than 1 application.
`Zwavejs2Mqtt` is 1 front end, `node-red-contrib-zwave-js` is another - they both achieve the same thing - controlling your network.

This module is strictly for node red, and if you want to use it, it will need exclusive rights over the serial port, like `Zwavejs2Mqtt` will need exclusive rights.

**Comment by devironglove** [comment]
Okido !

This is something I was afraid of. Just confirmed by disabling Zwave2Mqtt container for a while, and after multiple attempts, it paired.
I suppose I'll find a way to work with both  depending my needs :) 

Thanks for the quick answer !

**Comment by Andoramb** [comment]
I would like to know what workarounds are possible here.
Been running Zwavejs2Mqtt that's used mostly by HA, but this module could go around it and be independent from everything else.
But how to use it in both places?

**Comment by marcus-j-davies** [comment]
> I would like to know what workarounds are possible here.

I'm  afraid there are none

 - Zwavejs2Mqtt (now named ZWave JS UI)
 - node-red-contrib-zwave-js
 
 Are both 2 different frontends/UIs for zwave utilising the same backend driver.
 Each will connect to the serial port of the zwave radio, and each will handle the network.
 
 If you somehow created a hackery work around to allow the serial port to be opened by 2 different things
 (serial interfaces are not designed that way)  - I would imagine chaos!
 
 If you wanted to use Node RED to manage your ZWave - then nothing else must do (the associated services will need to stop), meaning HA will not see the network.
 
 likewise, if you were Using Node RED but wanted to switch to HA/Zwavejs2Mqtt then Node RED must not.

**Comment by Andoramb** [comment]
Yes, I agree. thank you for your time :)
