### ISSUE TITLE
TypeError: _Context.input is not a function

### ISSUE THREAD

**Issue by 0rsa** [zwave-js/node-red-contrib-zwave-js#78]
**Plugin Version**
4.0.0

**Platform**
Debian 10

**Describe the bug**
Z-wave control panel is empty

**To Reproduce**
Open Z-wave Panel and click on "Refresh node list"

**Debug Logs**
```
TypeError: _Context.input is not a function
    at node_modules/node-red-contrib-zwave-js/zwave-js/ui/server.js:108:16
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at query (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
```

Node-red 1.3.5
NodeJS 14.17.2

**Comment by marcus-j-davies** [comment]
Hi, has the driver loaded? You get this if you open the UI before things have managed to init.

**Comment by 0rsa** [comment]
It was probably an init error, you are right.

This is now working. I don't know if a browser restart or a node red solved issue, I did both.
Currently migrating from zme uzb1 to z-stick 7 and from your old 3.8.0 to 4.0.0, I had 2 instances of node-red-contrib-zwave-js launched with 2 different instances of node-red, I suppose that it does not help for a good startup.

I close this issue as this is resolved for me. Feel free to re open if you can improve first init to avoid this error.

Thank you very much for your quickly replies.

**Comment by marcus-j-davies** [comment]
It's an edge case, but I probably need to improve it still - it only occurs if the UI/NR is trying to query things when its being initialised - refreshing the page usually resolves it.

Remember to transition to the new API, the old message format is being removed.

Thank you

**Comment by 0rsa** [comment]
Yes, thank you for your guide, this is really appreciated.
This is my planned work for now :)

**Comment by marcus-j-davies** [comment]
You welcome.

Please raise a Help needed request, if you get stuck (And enjoy the map)
